---
- name: Create JVM directory
  file: path=/usr/lib/jvm state=directory
  tags: java

- name: Run JDK 6 installer
  shell: >
      creates=/usr/java/jdk1.6.0_45/bin/java
      free_form=true
      echo ''|/bin/sh /tmp/jdk-6u45-linux-x64-rpm.bin
  tags: java

- name: Copy alternatives script
  copy: src=alternatives.sh dest=/tmp/alternatives.sh mode=0755
  tags: java

- name: Configure Java alternatives
  shell: /tmp/alternatives.sh "1.6.0_45"
  register: command_result
  failed_when: "'FAILED' in command_result.stdout"
  changed_when: "'CHANGED' in command_result.stdout"
  tags: java

