---
- name: Merge PostgreSQL configuration files
  assemble: src={{ datadir }}/pg_hba.d dest={{ datadir }}/pg_hba.conf
  delegate_to: "{{ linshare_db_master_host }}"
  notify: 
    - Reload Postgres
  tags: linshare-db

- name: Reload Postgres
  service: name=postgresql state=reloaded
  delegate_to: "{{ linshare_db_master_host }}"
  tags: linshare-db
