---
- name: Clean yum repositories
  command: /usr/bin/yum clean all

- name: Start NTP server
  service: name=ntpd state=started enabled=yes

- name: Restart NTP service
  service: name=ntpd state=restarted

- name: Update system date
  command: ntpq -p
