---
- name: Create PostgreSQL configuration directory
  file: name={{ datadir }}/pg_hba.d state=directory
  tags: postgres

- name: Deploy PostgreSQL configuration header
  copy: src=00-header dest={{ datadir }}/pg_hba.d/00-header
  notify:
    - Merge PostgreSQL configuration files
  tags: postgres

- name: Deploy PostgreSQL local configuration
  copy: src=02-local-peer dest={{ datadir }}/pg_hba.d/02-local-peer
  notify:
    - Merge PostgreSQL configuration files
  tags: postgres

- name: Deploy PostgreSQL remote configuration
  copy: src=04-remote-ident dest={{ datadir }}/pg_hba.d/04-remote-ident
  notify:
    - Merge PostgreSQL configuration files
  tags: postgres

- name: Deploy PostgreSQL configuration footer
  copy: src=06-footer dest={{ datadir }}/pg_hba.d/06-footer
  notify:
    - Merge PostgreSQL configuration files
  tags: postgres
