---
- name: Install Python psycopg2
  yum: pkg=python-psycopg2
  tags: postgres

- name: Install PostgreSQL Server
  yum: pkg=postgresql91-server
  register: command_result
  tags: postgres

- name: Initialize PostgreSQL Server
  command: /etc/init.d/postgresql-9.1 initdb en_US.UTF-8
  when: command_result.changed
  tags: postgres

- name: Start PostgreSQL service
  service: name=postgresql-9.1 state=started enabled=yes
  tags: postgres

- name: Deploy PostgreSQL template1 correction script
  copy: src=correct_pg_template1.sql dest=/tmp/correct_pg_template1.sql
  when: command_result.changed
  tags: postgres

- name: Correct PostgreSQL default template (template1)
  command: su -l postgres -c "psql -f /tmp/correct_pg_template1.sql"
  when: command_result.changed
  tags: postgres

- name: Symlink for linshare-admin
  file: src={{ item.src }} dest={{ item.dest }} state=link
  with_items:
   - { src: '/etc/init.d/postgresql-9.1', dest: '/etc/init.d/postgresql' }
   - { src: '/var/lib/pgsql/9.1/data', dest: '/var/lib/pgsql/data' }
  tags: postgres
